sudo: false
language: node_js
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run test
  - npm run report-coverage
  - npm run docs:build
deploy:
  provider: pages
  local-dir: docs
  github-token: $GH_TOKEN
  skip-cleanup: true
  keep-history: true
  verbose: true
  on:
    branch: master
