sudo: false
language: node_js
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run test
  - npm run report-coverage
  - npm run build
after_success:
  - npm run semantic-release
