sudo: false
language: node_js
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run test
  - npm run report-coverage
  - npm run build
  - npm run docs:build
after_success:
  - npm run docs:publish
  - npm run semantic-release
